from utils import *

# logging level: NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Corpus of text taken from the Higgs boson outreach article I wrote for a Glasgow student science magazine
# https://the-gist.org/2015/06/the-higgs-boson-the-origin-of-mass-and-the-nature-of-space
LIST_CORPUS = [
    """{"paragraph1": "The largest particle accelerator in the world, the Large Hadron Collider (LHC) at CERN, starts taking data once again today, June 3rd 2015, after a two-year major upgrade. The detectors of the ATLAS and CMS collaborations first collected data between 2009 and 2012. Data analysis by their almost 3,000 strong international teams was profoundly successful. Both ATLAS and CMS discovered the same elementary particle with the same properties, independently of each other.", "paragraph2": "Elementary particles are the smallest known building blocks of atoms. The elementary particle discovered was predicted to exist half a century earlier by Professor Peter Higgs, of the University of Edinburgh. It’s also a boson, a subtype of elementary particles, hence its name: the Higgs boson.", "paragraph3": "The Universe has its present form – with stars, planets and life – because atoms exist and are stable. This happens because the elementary particles that atoms are made of are able to travel slower than the speed of light, the largest speed possible. The speed at which a particle can travel is determined by its mass. Particles with zero mass always travel at the speed of light. If a particle has a non-zero mass, even a very small one, it can be at rest or travel at slow speeds, but never reach the speed of light.", "paragraph4": "In the summer of 1964, a truly revolutionary idea appeared to explain the origin of mass of elementary particles. The idea came from two independent teams – Robert Brout and Francois Englert in Belgium, and Peter Higgs in Scotland, and it was this: imagine a dense forest, with a small person and a large person running through the trees. Who do you think arrives first on the other side of the forest? Indeed, the small person! Being small, he can squeeze between the trees more easily than the larger person, feeling a smaller “friction” from the forest. It turns out this situation is analogous to how elementary particles obtain mass."}""",
    """{"paragraph1": "Their extraordinary insight was that absolutely everywhere in the Universe – in objects, in humans, but even in the vacuum of cosmic space, where nothing should exist – there is something previously unknown. When in every point in space there is something, physicists call it a field, represented in our analogy by the forest. Two types of particles travelling through space, represented by the two people, feel a “friction” from this field, are slowed down from the speed of light, and thus acquire different masses. The larger the interaction of an elementary particle with the field, the larger its mass. In honour of the scientists who predicted it, scientists call it the Brout-Englert-Higgs (BEH) field.", "paragraph2": "Only Peter Higgs wrote explicitly in his paper something that the Belgium team did not as it was trivial knowledge at the time: every field has a corresponding particle, represented in our analogy by a tree. Just as a forest is made of trees, the field is made of particles.", "paragraph3": "In this way, Peter Higgs proposed the way to prove the existence of the BEH field: experiments must observe a new elementary particle having certain properties. In his honour, the particle is called the Higgs boson. Elementary particles feel a “friction” from the BEH field because they collide in fact with the Higgs bosons."}""",
    """{"paragraph1": "The discovery of the Higgs boson at CERN in 2012 confirmed, half a century since its creation, that the theory about the BEH field is a correct description of how elementary particles acquire mass. As a result, the theorists Francois Englert and Peter Higgs received the Nobel Prize for physics in 2013. Sadly, Robert Brout had passed away in 2011 without having seen his theory confirmed, and unable to receive a Nobel prize.", "paragraph2": "Measuring precisely the properties of the Higgs boson will guide theorists and experimentalists to search for phenomena as yet unknown. For example, it is known from studying the sky that the cosmic space contains, besides the normal matter made of atoms, about five times more matter not made of atoms. Scientists call it dark matter and believe it is made of a type of elementary particle not accounted for by the already known elementary particles. Several theories have appeared that extend the current theory, and in addition to the already known particles, predict the existence of dark matter particles. Interestingly, these theories also predict the existence of five Higgs bosons, including the one predicted by the current theory. Precise measurement of the properties of the newly discovered particle, as well as searching for unknown dark matter particles, is therefore key to searching for experimental hints about the new theories. There are hopes that these measurements and discoveries will be made during the data-taking starting once again at CERN. The accelerator will almost double the collision energy, allowing for the detection of unknown particles with twice the mass of those that could be detected before.", "paragraph3": "The fact that the BEH field exists everywhere in space suggests a deep connection between the field and the nature of space itself. This will guide theorists aspiring to find a more advanced theory of elementary particles. It also makes the author of this article dream about manipulating space with the help of Higgs bosons. The writers of the science-fiction series Star Trek claimed that although their spaceships travel to distant stars, they did not break the law that nothing is faster than the speed of light. Instead, space is manipulated around the spaceship in such a way that the ship – relative to space – is always going slower than light. Could Higgs bosons help to manipulate space? For now, one can only dream.", "paragraph4": "In the meantime, driven by curiosity, particle physicists continue to study the fundamental ingredients of matter, including the newly discovered Higgs boson. And who knows what discoveries the ATLAS and CMS experiments at CERN may bring, thanks to LHC’s recent facelift?"}""",
]

def main():
    for corpus in LIST_CORPUS:
        process_corpus(corpus)

if __name__ == '__main__':
    main()  # Standard boilerplate to call the main() function to begin the program.



